### ISSUE TITLE
aleph init should take a path to Python binary

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/aleph#2]
Currently, the `aleph` user seems to have minimal control over which Python their project environment uses (`--python python3` in `aleph.aleph_cli.init.generator.run` subprocess call).

It makes sense to take this from command line (optionally). I also wonder if we shouldn't allow users to specify an already existing virtualenv for their `aleph` project instead of forcing them to create a new one, but I don't have a strong opinion about this.

**Comment by phildow** [comment]
I had a hard time deciding how to handle the virtual environment. I'd like to follow the pattern rails and django use, so I'm going to look into that. And then it's interesting because the virtual environment required by the aleph cli isn't necessarily the same as the one required by the project. 

On the question of supporting a python binary, I'm not sure how to handle my code so that it's both 2.7 and 3.x compatible. I'll need some guidance there.

**Comment by phildow** [comment]
Closing given https://github.com/doc-ai/aleph/pull/5
